query CartTransformRunInput(
  $includeTags: [String!]
  $includeCollectionIds: [ID!]
  $excludeTags: [String!]
  $excludeCollectionIds: [ID!]
) {
  presentmentCurrencyRate
  cart {
    lines {
      id
      quantity
      cost {
        amountPerQuantity {
          amount
        }
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          title
          product {
            id
            title
            hasIncludedTag: hasAnyTag(tags: $includeTags)
            inIncludedCollection: inAnyCollection(ids: $includeCollectionIds)
            hasExcludedTag: hasAnyTag(tags: $excludeTags)
            inExcludedCollection: inAnyCollection(ids: $excludeCollectionIds)
          }
        }
      }
    }
  }
  cartTransform {
    metafield(namespace: "$app:deposit", key: "function-configuration") {
      value
    }
  }
}
