query RunInput(
  $includeCollectionIds: [ID!]
  $excludeCollectionIds: [ID!]
) {
  cart {
    lines {
      id
      quantity
      merchandise {
        __typename
        ... on ProductVariant {
          id
          title
          image {
            url
          }
          product {
            id
            title
            hasAnyTag(tags: [])
            inAnyCollection(ids: $includeCollectionIds)
          }
        }
      }
    }
  }
  cartTransform {
    metafield(namespace: "$app:deposit", key: "function-configuration") {
      value
    }
  }
}
