api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "deposit-cart-transform"
type = "function"
uid = "c9300a76-1705-abd5-d72b-e65a21b67ba6e1230842"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
